### ISSUE TITLE
MultiJVM tests for constructr-akka-testing failing

### ISSUE THREAD

**Issue by longshorej** [typesafehub/constructr-zookeeper#34]
I attempted to release this today but seem to be having some 2.11/2.12 bincompat issues. @markusjura have you seen this before? 

I get this when running `sbt +test`:

```bash
longshorej@ubuntu1604:~/releases/2017-11-06/constructr-zookeeper$ sbt +test
[info] Loading global plugins from /home/longshorej/.sbt/0.13/plugins
[info] Loading project definition from /home/longshorej/releases/2017-11-06/constructr-zookeeper/project
[info] Set current project to constructr-zookeeper-root (in build file:/home/longshorej/releases/2017-11-06/constructr-zookeeper/)
[info] Setting version to 2.12.4
[info] Reapplying settings...
[info] Set current project to constructr-zookeeper-root (in build file:/home/longshorej/releases/2017-11-06/constructr-zookeeper/)
[info] Updating {file:/home/longshorej/releases/2017-11-06/constructr-zookeeper/}constructr-coordination-zookeeper...
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] Updating {file:/home/longshorej/releases/2017-11-06/constructr-zookeeper/}constructr-akka-testing...
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] Run completed in 54 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] * com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpec
[JVM-3] Exception in thread "ScalaTest-main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
[JVM-3] 	at org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:184)
[JVM-3] 	at org.scalatest.tools.ArgsParser$.parseReporterArgsIntoConfigurations(ArgsParser.scala:586)
[JVM-3] 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:890)
[JVM-3] 	at org.scalatest.tools.Runner$.main(Runner.scala:827)
[JVM-3] 	at org.scalatest.tools.Runner.main(Runner.scala)
[JVM-4] Exception in thread "ScalaTest-main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
[JVM-4] 	at org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:184)
[JVM-4] 	at org.scalatest.tools.ArgsParser$.parseReporterArgsIntoConfigurations(ArgsParser.scala:586)
[JVM-4] 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:890)
[JVM-4] 	at org.scalatest.tools.Runner$.main(Runner.scala:827)
[JVM-4] 	at org.scalatest.tools.Runner.main(Runner.scala)
[JVM-2] Exception in thread "ScalaTest-main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
[JVM-2] 	at org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:184)
[JVM-2] 	at org.scalatest.tools.ArgsParser$.parseReporterArgsIntoConfigurations(ArgsParser.scala:586)
[JVM-2] 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:890)
[JVM-2] 	at org.scalatest.tools.Runner$.main(Runner.scala:827)
[JVM-2] 	at org.scalatest.tools.Runner.main(Runner.scala)
[JVM-5] Exception in thread "ScalaTest-main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
[JVM-5] 	at org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:184)
[JVM-5] 	at org.scalatest.tools.ArgsParser$.parseReporterArgsIntoConfigurations(ArgsParser.scala:586)
[JVM-5] 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:890)
[JVM-5] 	at org.scalatest.tools.Runner$.main(Runner.scala:827)
[JVM-5] 	at org.scalatest.tools.Runner.main(Runner.scala)
[JVM-1] Exception in thread "ScalaTest-main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
[JVM-1] 	at org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:184)
[JVM-1] 	at org.scalatest.tools.ArgsParser$.parseReporterArgsIntoConfigurations(ArgsParser.scala:586)
[JVM-1] 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:890)
[JVM-1] 	at org.scalatest.tools.Runner$.main(Runner.scala:827)
[JVM-1] 	at org.scalatest.tools.Runner.main(Runner.scala)
[error] Failed: com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpecMultiJvmNode1
[error] Failed: com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpecMultiJvmNode2
[error] Failed: com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpecMultiJvmNode3
[error] Failed: com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpecMultiJvmNode4
[error] Failed: com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpecMultiJvmNode5
[info] com.lightbend.constructr.coordination.zookeeper.MultiNodeZookeeperConstructrSpec
[info] No tests to run for MultiJvm
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] [11/06/2017 12:44:34.481] [pool-7-thread-2-ScalaTest-running-ZookeeperCoordinationSpec] [akka.actor.ActorSystemImpl(default)] Zookeeper client tries to establish a connection to nodes [127.0.0.1:2181]..
[info] ZookeeperCoordinationSpec:
[info] ZookeeperCoordination
[info] - should correctly interact with zookeeper
[info] ZookeeperNodesSpec:
[info] ZookeeperNodes
[info] - should should extract nodes from a list
[info] - should should extract ZK nodes from a string
[info] Run completed in 3 seconds, 854 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] (constructr-akka-testing/multi-jvm:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Nov 6, 2017 12:44:36 PM
[INFO] [11/06/2017 12:44:36.149] [default-shutdown-hook-1] [CoordinatedShutdown(akka://default)] Starting coordinated shutdown from JVM shutdown hook
[INFO] [11/06/2017 12:44:36.152] [default-shutdown-hook-1] [CoordinatedShutdown(akka://default)] Starting coordinated shutdown from JVM shutdown hook
```

**Comment by markusjura** [comment]
@longshorej This seems like a local issue. Don't get such exception when running `sbt +test` on `master`. Make sure to clean all target folder of sbt. A command that does it on OSX is:

```
find . -name target -exec rm -rf "{}" \;
```

**Comment by longshorej** [comment]
Hrm - was a fresh clone of the project on a Ubuntu 16.04 VM. I'll circle back to it at some point.

**Comment by amarouni** [comment]
@markusjura @longshorej Any updates guys ? Do you need any help ?
This seem to block the release.

**Comment by markusjura** [comment]
@amarouni I am very sorry that I haven't spent time on this yet. Need to dig into the topic why cross releasing is not possible. It was working before. Doing that latest on the next weekend. Sorry for the delay.
